tap "kkensuke/tap", "https://github.com/kkensuke/homebrew-tap.git", trusted: true
tap "nikitabobko/tap"
tap "rgeraskin/homebrew"
tap "timac/vpnstatus"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Console Matrix
brew "cmatrix"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Disk Usage/Free Utility - a better 'df' alternative
brew "duf"
# More intuitive version of du in rust
brew "dust"
# Select default apps for documents and URL schemes on macOS
brew "duti"
# Modern, maintained replacement for ls
brew "eza"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU compiler collection
brew "gcc"
# GitHub command-line tool
brew "gh"
# Interpreter for PostScript and PDF
brew "ghostscript"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Quickly rewrite git repository history
brew "git-filter-repo"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Program providing model for GNU coding standards and practices
brew "hello"
# Pager program similar to more
brew "less"
# LLVM's OpenMP runtime library
brew "libomp"
# Mac App Store command-line interface
brew "mas"
# Deep clean and optimize your Mac
brew "mole"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Fast, disk space efficient package manager
brew "pnpm"
# Perl-powered file rename script with many helpful built-ins
brew "rename"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Safe, concurrent, practical language
brew "rust"
# Fast and accurate code counter with complexity and COCOMO estimates
brew "scc"
# Change macOS audio source from the command-line
brew "switchaudio-osx"
# CLI tool that moves files or folder to the trash
brew "trash"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Feature-rich command-line audio/video downloader
brew "yt-dlp"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Additional completion definitions for zsh
brew "zsh-completions"
# Informative git prompt for zsh
brew "zsh-git-prompt"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# A symbolic-link management CLI for macOS
brew "kkensuke/tap/slink"
# Memory training application
cask "anki"
# Application uninstaller
cask "appcleaner"
# Virtual Audio Driver
cask "blackhole-2ch"
# Clipboard extension app
cask "clipy"
# Free app that makes your Internet safer
cask "cloudflare-warp"
# Tool to show live information about the batteries in various devices
cask "coconutbattery"
# Multi-platform client-side cloud file encryption tool
cask "cryptomator"
# Online diagram software
cask "drawio"
# Cross-platform Text Expander written in Rust
cask "espanso"
cask "font-jetbrains-mono-nerd-font"
cask "font-sf-mono-nerd-font-ligaturized"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Client for the Google Drive storage service
cask "google-drive"
# Free and open-source media player
cask "iina"
# Open-source keystroke visualiser
cask "keycastr"
# Backup/restore tool
cask "kopiaui"
# Scanner app for math and science
cask "mathpix-snipping-tool"
# Tool to control external monitor brightness & volume
cask "monitorcontrol"
# Quick Look generator for Markdown files
cask "qlmarkdown"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Screenshot measurement and annotation tool
cask "shottr"
# System monitor for the menu bar
cask "stats"
# Quicklook extension for source files
cask "syntax-highlight"
# Open-source code editor
cask "visual-studio-code"
cask "vpnstatus"
# Video communication and virtual meeting platform
cask "zoom"
# Collect, organise, cite, and share research sources
cask "zotero"
mas "DropNote", id: 6761221463
mas "Hand Mirror", id: 1502839586
mas "Keynote", id: 361285480
mas "Kindle", id: 302584613
mas "LINE", id: 539883307
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
vscode "aaron-bond.better-comments"
vscode "adpyke.codesnap"
vscode "bradlc.vscode-tailwindcss"
vscode "dbaeumer.vscode-eslint"
vscode "dsznajder.es7-react-js-snippets"
vscode "executablebookproject.myst-highlight"
vscode "formulahendry.auto-rename-tag"
vscode "formulahendry.code-runner"
vscode "hediet.vscode-drawio"
vscode "james-yu.latex-workshop"
vscode "janisdd.vscode-edit-csv"
vscode "mechatroner.rainbow-csv"
vscode "ms-azuretools.vscode-containers"
vscode "ms-toolsai.datawrangler"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpp-devtools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vsliveshare.vsliveshare"
vscode "njpwerner.autodocstring"
vscode "oderwat.indent-rainbow"
vscode "phoihos.csv-to-md-table"
vscode "pkief.material-icon-theme"
vscode "prisma.prisma"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "streetsidesoftware.code-spell-checker"
vscode "tamasfe.even-better-toml"
vscode "trapfether.tailwind-raw-reorder"
vscode "twxs.cmake"
vscode "uctakeoff.vscode-counter"
vscode "usernamehw.errorlens"
vscode "yzhang.markdown-all-in-one"
uv "pypistats"
uv "yttext[web]"
